DROP TABLE IF EXISTS Enrollment;

DROP TABLE IF EXISTS User;

CREATE TABLE IF NOT EXISTS User (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Course;

CREATE TABLE IF NOT EXISTS Course (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS Enrollment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    dateenrollment date NOT NULL,
    username VARCHAR(20) NOT NULL,
    fk_course BIGINT NOT NULL,
    fk_user BIGINT NOT NULL,
    FOREIGN KEY(fk_course) REFERENCES Course(id),
    FOREIGN KEY(fk_user) REFERENCES User(id)    
);


